<a href="https://colab.research.google.com/github/artem-dorofeev/py_DataScience_HW/blob/main/hw1_py_ds.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [ ]:
import numpy as np
vector = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int)
print(vector)

[0 1 2 3 4 5 6 7 8 9]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [ ]:
matrix = np.array([[0, 0, 0], [0, 0, 0]], dtype=int)

print(matrix)

[[0 0 0]
 [0 0 0]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [ ]:
matrix_3 = np.random.randint(1, 11, size=(5, 5))

print(matrix_3)

[[ 9  9  8  9  1]
 [ 1 10  9  5  1]
 [ 2  8  9  3  3]
 [ 1  8  3  5  5]
 [ 7  5  1  4 10]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [ ]:
matrix_4 = np.random.rand(4, 4)

print(matrix_4)

[[0.86969782 0.13844036 0.3724723  0.87764129]
 [0.00473141 0.399659   0.9090419  0.13854354]
 [0.73785857 0.65145742 0.40081291 0.75729305]
 [0.93431243 0.15221811 0.27796643 0.83717475]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [ ]:
matrix_5_1 = np.random.randint(1, 11, size=(5, 5))
matrix_5_2 = np.random.randint(1, 11, size=(5, 5))

m_sum = matrix_5_1 + matrix_5_2
m_sub = matrix_5_1 - matrix_5_2
m_mult = matrix_5_1 * matrix_5_2

# print(f"{matrix_5_1} \n\n {matrix_5_2} \n\n {m_sum} \n\n {m_sub} \n\n {m_mult}")


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [ ]:
vector_6_1 = np.random.randint(1, 11, size=(7))
vector_6_2 = np.random.randint(1, 11, size=(7))

v_scalar = np.dot(vector_6_1, vector_6_2)

# print(f"{vector_6_1} \n\n {vector_6_2} \n\n {vector_6_1 * vector_6_2} \n\n {v_scalar}")


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [ ]:
matrix_7_1 = np.random.randint(1, 11, size=(2, 2))
matrix_7_2 = np.random.randint(1, 11, size=(2, 3))

m_dot = np.dot(matrix_7_1, matrix_7_2)

# print(f"{matrix_7_1} \n \n {matrix_7_2} \n\n {m_dot}")

8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [ ]:
matrix_8_1 = np.random.rand(3, 3)

m_inv = np.linalg.inv(matrix_8_1)

# print(f"{matrix_8_1} \n \n {m_inv}")

9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [ ]:
matrix_9_1 = np.random.randint(1, 11, size=(4, 4))

m_trans = matrix_9_1.T

# print(f"{matrix_9_1} \n \n {m_trans}")

10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [ ]:
matrix_10_1 = np.random.randint(1, 11, size=(3, 4))
vector_10_1 = np.random.randint(1, 11, size=(4))

m_dot_v = np.dot(matrix_10_1, vector_10_1)

# print(f"{matrix_10_1} \n \n {vector_10_1} \n \n {m_dot_v}")


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [ ]:
matrix_11_1 = np.random.rand(2, 3)
vector_11_1 = np.random.rand(3)

m_dot_v = np.dot(matrix_11_1, vector_11_1)

# print(f"{matrix_11_1} \n \n {vector_11_1} \n \n {m_dot_v}")

12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [ ]:
matrix_12_1 = np.random.randint(1, 11, size=(2, 2))
matrix_12_2 = np.random.randint(1, 11, size=(2, 2))

m_mult = matrix_12_1 * matrix_12_2

# print(f"{matrix_12_1} \n\n {matrix_12_2} \n\n {m_mult}")

13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [ ]:
matrix_13_1 = np.random.randint(1, 11, size=(2, 2))
matrix_13_2 = np.random.randint(1, 11, size=(2, 2))

m_dot = np.dot(matrix_13_1, matrix_13_2)

# print(f"{matrix_13_1} \n\n {matrix_13_2} \n\n {m_dot}")

14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [ ]:
matrix_14_1 = np.random.randint(1, 101, size=(5, 5))

m_sum = np.sum(matrix_14_1)

# print(f"{matrix_14_1} \n\n {m_sum}")

15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [ ]:
matrix_15_1 = np.random.randint(1, 11, size=(4, 4))
matrix_15_2 = np.random.randint(1, 11, size=(4, 4))

m_sub = matrix_15_1 - matrix_15_2

# print(f"{matrix_15_1} \n\n {matrix_15_2} \n\n {m_sub}")

16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [ ]:
matrix_16_1 = np.random.rand(3, 3)

v_sums = np.sum(matrix_16_1, axis=1, keepdims=True)
# v_sums2 = np.sum(matrix_16_1, axis=1, keepdims=False)

# print(f"{matrix_16_1} \n\n {v_sums} \n\n {v_sums2}")

17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [ ]:
matrix_17_1 = np.random.randint(1, 11, size=(3, 4))

m_squa = np.square(matrix_17_1)

# print(f"{matrix_17_1} \n\n {m_squa}")

18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [ ]:
vector_18_1 = np.random.randint(1, 51, size=(4))

v_sqrt = np.sqrt(vector_18_1)

# print(f"{vector_18_1} \n\n {v_sqrt }")
