<a href="https://colab.research.google.com/github/artem-dorofeev/py_DataScience_HW/blob/main/hw1_py_ds.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [1]:
import numpy as np
vector = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int)
print(vector)

[0 1 2 3 4 5 6 7 8 9]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [2]:
matrix = np.array([[0, 0, 0], [0, 0, 0]], dtype=int)

print(matrix)

[[0 0 0]
 [0 0 0]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [3]:
matrix_3 = np.random.randint(1, 11, size=(5, 5))

print(matrix_3)

[[ 1 10 10  6  1]
 [10  3  9  1  3]
 [ 5  3  5  9  2]
 [ 4  7  3  3  8]
 [ 8  5 10  7 10]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [4]:
matrix_4 = np.random.rand(4, 4)

print(matrix_4)

[[0.68830176 0.43072494 0.24004444 0.85933608]
 [0.32001878 0.05478612 0.22672464 0.84264328]
 [0.15148119 0.80874924 0.17590954 0.81662632]
 [0.27016514 0.03457038 0.5480271  0.49061507]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [6]:
matrix_5_1 = np.random.randint(1, 11, size=(5, 5))
matrix_5_2 = np.random.randint(1, 11, size=(5, 5))

m_sum = matrix_5_1 + matrix_5_2
m_sub = matrix_5_1 - matrix_5_2
m_mult = matrix_5_1 * matrix_5_2

print(f"{matrix_5_1} \n\n {matrix_5_2} \n\n {m_sum} \n\n {m_sub} \n\n {m_mult}")


[[ 6  4  3  6  2]
 [ 5  6  8  4  7]
 [ 3  4  6  8 10]
 [10  1  5  8  2]
 [ 2  6  3  5  7]] 

 [[ 7  7  6  3 10]
 [ 3  9  5  5  7]
 [ 1  8  9  4  3]
 [ 8  5  2  4 10]
 [10  4  1  3 10]] 

 [[13 11  9  9 12]
 [ 8 15 13  9 14]
 [ 4 12 15 12 13]
 [18  6  7 12 12]
 [12 10  4  8 17]] 

 [[-1 -3 -3  3 -8]
 [ 2 -3  3 -1  0]
 [ 2 -4 -3  4  7]
 [ 2 -4  3  4 -8]
 [-8  2  2  2 -3]] 

 [[42 28 18 18 20]
 [15 54 40 20 49]
 [ 3 32 54 32 30]
 [80  5 10 32 20]
 [20 24  3 15 70]]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [7]:
vector_6_1 = np.random.randint(1, 11, size=(7))
vector_6_2 = np.random.randint(1, 11, size=(7))

v_scalar = np.dot(vector_6_1, vector_6_2)

print(f"{vector_6_1} \n\n {vector_6_2} \n\n {vector_6_1 * vector_6_2} \n\n {v_scalar}")


[3 4 5 7 1 3 2] 

 [6 4 6 6 3 7 8] 

 [18 16 30 42  3 21 16] 

 146


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [8]:
matrix_7_1 = np.random.randint(1, 11, size=(2, 2))
matrix_7_2 = np.random.randint(1, 11, size=(2, 3))

m_dot = np.dot(matrix_7_1, matrix_7_2)

print(f"{matrix_7_1} \n \n {matrix_7_2} \n\n {m_dot}")

[[4 7]
 [2 7]] 
 
 [[ 9 10  4]
 [ 8  3  2]] 

 [[92 61 30]
 [74 41 22]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [9]:
matrix_8_1 = np.random.rand(3, 3)

m_inv = np.linalg.inv(matrix_8_1)

print(f"{matrix_8_1} \n \n {m_inv}")

[[0.85381565 0.49693708 0.08763359]
 [0.41414355 0.3458976  0.46071595]
 [0.90626161 0.43371345 0.90515885]] 
 
 [[ 1.06674979 -3.87810366  1.8706342 ]
 [ 0.40178179  6.53025662 -3.36272795]
 [-1.2605661   0.75380843  0.84314082]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [10]:
matrix_9_1 = np.random.randint(1, 11, size=(4, 4))

m_trans = matrix_9_1.T

print(f"{matrix_9_1} \n \n {m_trans}")

[[10  1  9  6]
 [ 2  5  8  2]
 [ 7  6  7  9]
 [ 5  4  3  6]] 
 
 [[10  2  7  5]
 [ 1  5  6  4]
 [ 9  8  7  3]
 [ 6  2  9  6]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [11]:
matrix_10_1 = np.random.randint(1, 11, size=(3, 4))
vector_10_1 = np.random.randint(1, 11, size=(4))

m_dot_v = np.dot(matrix_10_1, vector_10_1)

print(f"{matrix_10_1} \n \n {vector_10_1} \n \n {m_dot_v}")


[[7 9 2 3]
 [5 4 2 5]
 [8 2 4 7]] 
 
 [6 6 9 1] 
 
 [117  77 103]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [12]:
matrix_11_1 = np.random.rand(2, 3)
vector_11_1 = np.random.rand(3)

m_dot_v = np.dot(matrix_11_1, vector_11_1)

print(f"{matrix_11_1} \n \n {vector_11_1} \n \n {m_dot_v}")

[[0.73766966 0.48982761 0.42432426]
 [0.65618213 0.56187322 0.28673851]] 
 
 [0.4812314  0.70499163 0.3515041 ] 
 
 [0.84946588 0.81268112]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [13]:
matrix_12_1 = np.random.randint(1, 11, size=(2, 2))
matrix_12_2 = np.random.randint(1, 11, size=(2, 2))

m_mult = matrix_12_1 * matrix_12_2

print(f"{matrix_12_1} \n\n {matrix_12_2} \n\n {m_mult}")

[[4 5]
 [4 2]] 

 [[10 10]
 [ 4  6]] 

 [[40 50]
 [16 12]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [14]:
matrix_13_1 = np.random.randint(1, 11, size=(2, 2))
matrix_13_2 = np.random.randint(1, 11, size=(2, 2))

m_dot = np.dot(matrix_13_1, matrix_13_2)

print(f"{matrix_13_1} \n\n {matrix_13_2} \n\n {m_dot}")

[[ 1  3]
 [ 1 10]] 

 [[4 2]
 [7 7]] 

 [[25 23]
 [74 72]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [15]:
matrix_14_1 = np.random.randint(1, 101, size=(5, 5))

m_sum = np.sum(matrix_14_1)

print(f"{matrix_14_1} \n\n {m_sum}")

[[90 48 86 18 50]
 [68 80 98 75 46]
 [24 57 83 82 29]
 [77 36 97 50 63]
 [44 76 14 16 73]] 

 1480


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [16]:
matrix_15_1 = np.random.randint(1, 11, size=(4, 4))
matrix_15_2 = np.random.randint(1, 11, size=(4, 4))

m_sub = matrix_15_1 - matrix_15_2

print(f"{matrix_15_1} \n\n {matrix_15_2} \n\n {m_sub}")

[[ 4  1  8  1]
 [10  5  8  3]
 [ 4  1  5 10]
 [ 6  6  9  1]] 

 [[10  2  4  2]
 [ 7  4  2  7]
 [ 6  9  7  4]
 [ 4  1  1  1]] 

 [[-6 -1  4 -1]
 [ 3  1  6 -4]
 [-2 -8 -2  6]
 [ 2  5  8  0]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [17]:
matrix_16_1 = np.random.rand(3, 3)

v_sums = np.sum(matrix_16_1, axis=1, keepdims=True)
# v_sums2 = np.sum(matrix_16_1, axis=1, keepdims=False)

print(f"{matrix_16_1} \n\n {v_sums} ")

[[0.31983966 0.99420701 0.77385324]
 [0.85806804 0.62296717 0.53356337]
 [0.67805022 0.5832313  0.90583958]] 

 [[2.08789991]
 [2.01459857]
 [2.1671211 ]] 


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [18]:
matrix_17_1 = np.random.randint(1, 11, size=(3, 4))

m_squa = np.square(matrix_17_1)

print(f"{matrix_17_1} \n\n {m_squa}")

[[ 4  2 10  1]
 [ 1  1  1  6]
 [ 4  2  6  7]] 

 [[ 16   4 100   1]
 [  1   1   1  36]
 [ 16   4  36  49]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [19]:
vector_18_1 = np.random.randint(1, 51, size=(4))

v_sqrt = np.sqrt(vector_18_1)

print(f"{vector_18_1} \n\n {v_sqrt }")


[40  4  7  2] 

 [6.32455532 2.         2.64575131 1.41421356]
